name: publish Docker images
on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup params
        id: steps_id
        run: echo "::set-output name=number::$(123)"
      - name: github params
        run: |
          echo ${{github.actor}}
          echo ${{env.mascot}}
          echo ${{steps.steps_id.number}}
          if [[${{steps.steps_id.number}} > 10]];then echo > 10;else echo < 10

      # - name: publish docker images to github packages
      #   uses: VaultVulp/gp-docker-action@1.2.0
      #   with:
      #     github-token: ${{secrets.MY_TOKEN}}
      #     image-name: review-images
      #     dockerfile: Dockerfile
      # - name: deploy
      #   uses: JamesIves/github-pages-deploy-action@v4.4.0
      #   with:
      #     token: ${{secrets.MY_TOKEN}}
      #     branch: gh-pages
      #     folder: ./App/build
